runtime: go
api_version: go1

handlers:
  - url: /
    static_files: index.html
    upload: index.html
    secure: always
    login: required

  - url: /bundle.js
    static_files: bundle.js
    upload: bundle.js
    secure: always

  - url: /elm.js
    static_files: elm.js
    upload: elm.js
    secure: always

  - url: /finmgr.UserService/.*
    script: _go_app
    secure: always
    login: required

skip_files:
   - ^elm-stuff/.*
   - ^node_modules/.*
   - ^hbci/.*
