runtime: go
api_version: go1

handlers:
  - url: /
    static_files: index.html
    upload: index.html
    secure: always
    login: required

  - url: /manifest.json
    static_files: manifest.json
    upload: manifest.json
    secure: always

  - url: /index.js
    static_files: index.js
    upload: index.js
    secure: always

  - url: /worker.js
    static_files: worker.js
    upload: worker.js
    secure: always

  - url: /index.js.map
    static_files: index.js.map
    upload: index.js.map
    secure: always

  - url: /worker
    script: _go_app
    login: admin

  - url: /finmgr.UserService/.*
    script: _go_app
    secure: always
    login: required

  - url: /finmgr.AccountService/.*
    script: _go_app
    secure: always
    login: required

  - url: /finmgr.PushService/.*
    script: _go_app
    secure: always
    login: required

  - url: /web-push/publicKey
    script: _go_app
    secure: always

skip_files:
   - .*/elm-stuff/.*
   - .*/node_modules/.*
