runtime: go
api_version: go1

handlers:
  - url: /
    static_files: index.html
    upload: index.html
    secure: always
    login: required

  - url: /index.js
    static_files: index.js
    upload: index.js
    secure: always

  - url: /index.js.map
    static_files: index.js.map
    upload: index.js.map
    secure: always

  - url: /finmgr.UserService/.*
    script: _go_app
    secure: always
    login: required

skip_files:
   - .*/elm-stuff/.*
   - .*/node_modules/.*
