runtime: go
api_version: go1

handlers:
  - url: /
    static_files: index.html
    upload: index.html
    secure: always

  - url: /bundle.js
    static_files: build/bundle.js
    upload: build/bundle.js
    secure: always

  - url: /elm.js
    static_files: build/elm.js
    upload: build/elm.js
    secure: always

  - url: /pb.Service/.*
    script: _go_app
    secure: always

skip_files:
   - ^elm-stuff/.*
   - ^node_modules/.*
