runtime: go
api_version: go1

handlers:
  - url: /
    static_files: index.html
    upload: index.html
    secure: always

  - url: /bundle.js
    static_files: build/bundle.js
    upload: build/bundle.js
    secure: always

  - url: /api/.*
    script: _go_app
    secure: always

